### ISSUE TITLE
Investigate appropriate framework for mobile native implementation

### ISSUE THREAD

**Issue by haocencol** [vineesh92/Team-5-Comp-313-001-#1]

**Comment by haocencol** [comment]
@vineesh92 which frameworks were investigated and why?  Attach a file to this issue explaining the process that led to the framework your team finally decided to use.

**Comment by jithinjoshy121** [comment]
React Native framework and Android studio IDE are  the platforms we investigated to develop this application.Finally we decided on Android Studio IDE.
First of all, we were using Android Studio IDE for developing mobile applications in Subject:Mobile application development of semester 3. This experience help us to create a mobile application in android studio IDE in fast and efficient manner.
Second, there are lot of tutorials available for Android Studio IDE, which help us to solve any issues that we come across during the development phase.
Debugging is much easier in Android Studio.
The new interface design in Android Studio is faster, responds to changes more rapidly and has more customization options.
